[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc = "0.8.28"
via_ir = true
[fuzz]
runs = 1000000
max_test_rejects = 1000000
[invariant]
runs = 10000
shrink_run_limit = 10000



[[profile.default.fs_permissions]]
access = "read"
path = "./testdata"

[[profile.default.fs_permissions.fs_permissions]]
access = "read"
path = "./testdata"

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.1.0"
vlayer = "0.1.0-nightly-20241115-70dfc11"
risc0-ethereum = { version = "1.0.0", url = "https://github.com/vlayer-xyz/risc0-ethereum/releases/download/v1.0.0-soldeer-no-remappings/contracts.zip" }
